name: Deploy Dev

on: [workflow_dispatch]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Install NPM dependencies
      run: npm install
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }} --profile YaListoApp
    - name: Create env file
      run: |
        cat > env.json << EOF
        {
          "prod": {
            "MONGODBCONNECTION": "${{ secrets.AWS_KEY }}",
            "JWT_SECRET": ""
          },
          "dev": {
            "MONGODBCONNECTION": ${{ secrets.AWS_SECRET }},
            "JWT_SECRET": ""
          }
        }
        EOF
    - name: Print env.json
      run: cat env.json
    # Optional
    #- name: Build assets
    #  run: npm run assets-dev
    - name: Deploy Lambda functions
      run: serverless deploy --stage dev